apiVersion: v2
name: vkpr
version: 0.7.2
appVersion: v1.4.0
home: https://github.com/vertigobr/vkpr
icon: https://vertigo.com.br/wp-content/uploads/favicon.png
description: VKPR Helm chart (Vertigo Kubernetes Production Runtime)
keywords:
  - vkpr
  - production runtime
maintainers:
  - name: Vertigo
    email: devops@vertigo.com.br
sources:
  - https://github.com/vertigobr/vkpr
dependencies:
  ### INGRESS STACK ###
  - name: external-dns
    repository: https://charts.bitnami.com/bitnami
    version: 3.2.2
    condition: external-dns.enabled

  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.34.3
    condition: nginx-ingress.enabled

  ### LOGGING STACK ###
  - name: loki-stack
    repository: https://grafana.github.io/loki/charts
    version: 0.37.0
    condition: loki-stack.enabled
#
# LOGGING STACK
#
# ELK STACK
# - name: fluentd-elasticsearch
#   repository: https://kiwigrid.github.io
#   version: 5.3.1
#   condition: fluentd-elasticsearch.enabled
# - name: elasticsearch
#   repository: https://helm.elastic.co
#   version: 7.5.0
#   condition: elasticsearch.enabled
# - name: kibana
#   repository: https://helm.elastic.co
#   version: 7.5.0
#   condition: kibana.enabled

# GRAYLOG STACK
# - name: elasticsearch
#  repository: https://helm.elastic.co
#  version: 6.5.0 # nao pode ser 7 por causa do graylog
  # 6.6.2-alpha1
  # 6.5.0
#  condition: elasticsearch.enabled
# - name: graylog
#  repository: https://kubernetes-charts.storage.googleapis.com
#  version: 1.6.2
#  condition: graylog.enabled
# - name: mongodb-replicaset
#  repository: https://kubernetes-charts.storage.googleapis.com
#  version: 3.14.1
#  condition: mongodb-replicaset.enabled
# - name: fluent-bit
#   repository: https://kubernetes-charts.storage.googleapis.com
#   version: 2.8.5
#   condition: fluent-bit.enabled

  ### MONITORING STACK ###
  - name: prometheus-operator
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 8.12.3
    condition: prometheus-operator.enabled

# - name: metrics-server
#   repository: https://kubernetes-charts.storage.googleapis.com
#   version: 2.8.8
#   condition: metrics-server.enabled

# - name: metricbeat
#   repository: https://helm.elastic.co
#   version: 7.5.0
#   condition: metricbeat.enabled

# - name: kube-state-metrics
#   repository: https://kubernetes-charts.storage.googleapis.com
#   version: 2.4.1
#   condition: kube-state-metrics.enabled

  ### SECURITY STACK ###
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.0.1
    condition: cert-manager.enabled

  - name: keycloak
    repository: https://codecentric.github.io/helm-charts
    version: 8.2.2
    condition: keycloak.enabled

  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.5.0
    condition: vault.enabled

  ### BACKUP STACK ###
  - name: velero
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 2.7.4
    condition: velero.enabled
