#
# Valores para testes na digitalocean do chart e de suas dependÃªncias.
# Note o uso de dois LBs (kong/apis e traefik/webapps).
# NAO CONFUNDIR com o values.yaml interno do Chart que define seus defaults.
#
# O token da digitalocean deve ser fornecido na linha de comando:
#
# helm upgrade -i -f values-do.yaml vkpr ./vkpr \
#   --set external-dns.digitalocean.apiToken=$DO_AUTH_TOKEN

#
# INGRESS STACK
#
nginx-ingress:
  enabled: true
  controller:
    publishService:
      enabled: true


external-dns:
  enabled: true
  image:
    tag: 0.7.2-debian-10-r49
  policy: sync  
  rbac:
    create: true
  sources:
    - ingress
    - service
  provider: digitalocean
  interval: "1m"

cert-manager:
  enabled: true
  ingressShim:
    defaultIssuerName: letsencrypt-production
    defaultIssuerKind: ClusterIssuer
    defaultIssuerGroup: cert-manager.io
  installCRDs: false
  
# dados para o CRD do ACME
acme:
  email: andre@vertigo.com.br

# chart values
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
  - host: whoami.api.vertigo.com.br
    paths: ["/"]
  tls:
  - hosts:
    - whoami.api.vertigo.com.br
    secretName: whoami-cert

#
# LOGGING STACK
#
# ELK - COMENTADO
# fluentd-elasticsearch:
#   enabled: false
#   elasticsearch:
#     host: elasticsearch-master
# elasticsearch:
#   enabled: false
# kibana:
#   enabled: false
#   ingress:
#     enabled: true
#     annotations:
#       kubernetes.io/ingress.class: nginx
#       kubernetes.io/tls-acme: "true"
#     path: /
#     hosts:
#       - kibana.api.vertigo.com.br
#     tls:
#     - hosts:
#       - kibana.api.vertigo.com.br
#       secretName: kibana-vkpr-cert

# GRAYLOG
#
# tags do subchart graylog - SAO TOP LEVEL SEMPRE
tags:
  install-elasticsearch: false
  install-mongodb: false
elasticsearch:
  enabled: false
  volumeClaimTemplate:
    storageClassName: "do-block-storage"
# mongodb do graylog
mongodb-replicaset:
  enabled: false
  replicas: 1
graylog:
  enabled: false
  graylog:
    elasticsearch:
      hosts: "http://elasticsearch-master:9200"
    mongodb:
      uri: mongodb://vkpr-mongodb-replicaset-client:27017/databasename?replicaSet=rs0
    rootPassword: vert1234vert1234
    input:
      tcp:
        service:
          type: ClusterIP
        ports:
          - name: gelf-tcp
            port: 12201
      udp:
        service:
          type: ClusterIP
        ports:
          - name: gelf-udp
            port: 12201
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
        - graylog.api.vertigo.com.br
      tls:
        - hosts:
          - graylog.api.vertigo.com.br
          secretName: graylog-vkpr-cert

loki-stack:
  enabled: true

#
# MONITORING STACK
#
prometheus-operator:
  enabled: true
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: do-block-storage
            resources:
              requests:
                storage: 5Gi
  prometheus-node-exporter:
    service:
      port: 30206
      targetPort: 30206               
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: do-block-storage
            resources:
              requests:
                storage: 5Gi
  grafana:
    image:
      repository: vertigo/grafana
      tag: 7.0.0
    adminPassword: "vertigo"
    persistence:
      enabled: true
      storageClassName: do-block-storage
      accessModes: ["ReadWriteOnce"]
      size: 5Gi  
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts: ["grafana.api.vertigo.com.br"]
      tls:
      - hosts:
        - grafana.api.vertigo.com.br
        secretName: grafana-vkpr-cert

    grafana.ini:
      server:
        root_url: "https://grafana.api.vertigo.com.br"
      auth.generic_oauth:
        enabled: true
        scopes: openid profile email
        client_id: grafana
        # temporario -->
        client_secret: ""
        # <--
        auth_url: http://keycloak.api.vertigo.com.br/auth/realms/vkpr/protocol/openid-connect/auth
        token_url: http://keycloak.api.vertigo.com.br/auth/realms/vkpr/protocol/openid-connect/token
        api_url: http://keycloak.api.vertigo.com.br/auth/realms/vkpr/protocol/openid-connect/userinfo
        allowed_domains: api.vertigo.com.br vertigo.com.br
        allow_sign_up: true
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false


# BEATS - INICIO
# NAO FUNCIONA AINDA (BEATS)
# metric-beat embutido (sem subchart)
# metricbeat:
#  enabled: false
# metrics-server:
#   enabled: false
#   rbac:
#     create: true
#   args: ["--v=4","--kubelet-preferred-address-types=InternalIP","--kubelet-insecure-tls"]
#   hostNetwork:
#     enabled: true
# kube-state-metrics:
#   enabled: false
# BEATS - FIM

#
# SECURITY STACK
#
vault:
  enabled: false
  server:
    ha:
      enabled: true
      raft:
        enabled: true
#    dev:
#      enabled: true


keycloak:
  enabled: true
  prometheus:
    operator:
      enabled: true
      serviceMonitor:
        namespace: "vkpr" 
        selector:
          release: "vkpr"
  keycloak:
    username: keycloak
    password: admin123
    extraInitContainers: |
       - name: extensions
         image: busybox
         imagePullPolicy: IfNotPresent
         command:
           - sh
         args:
           - -c
           - |
             echo "Copying extensions..."
             wget -O /deployments/keycloak-metrics-spi.jar https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.1/keycloak-metrics-spi-1.0.1.jar
         volumeMounts:
          - name: deployments
            mountPath: /deployments
    persistence:
      dbVendor: h2
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
        - keycloak.api.vertigo.com.br
      tls:
        - hosts:
          - keycloak.api.vertigo.com.br
          secretName: keycloak-vkpr-cert
    extraVolumes: |
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data-volume
      - name: vkpr-realm-secret
        secret:
          secretName: vkpr-realm-secret
      - name: deployments
        emptyDir: {}

    extraVolumeMounts: |
      - name: keycloak-data
        mountPath: "/opt/jboss/keycloak/standalone/data"
        readOnly: false
      - name: vkpr-realm-secret
        mountPath: "/realm/"
        readOnly: true
      - name: deployments
        mountPath: /opt/jboss/keycloak/standalone/deployments

    extraEnv: |
      - name: KEYCLOAK_IMPORT
        value: /realm/realm-realm-export.json
      - name: KEYCLOAK_STATISTICS
        value: all
        
# BACKUP STACK
velero:
  enabled: false
  image:
    repository: velero/velero
    tag: v1.3.1
    pullPolicy: IfNotPresent

  podAnnotations: {}

  resources: {}

  initContainers: 
    - name: velero-plugin-for-do
      image: digitalocean/velero-plugin:v1.0.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.0.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  securityContext: {}

  tolerations: []

  nodeSelector: {}

  extraVolumes: []

  extraVolumeMounts: []

  metrics:
    enabled: true
    scrapeInterval: 30s

    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8085"
      prometheus.io/path: "/metrics"

    serviceMonitor:
      enabled: false
      additionalLabels: {}

  installCRDs: true

  configuration:
    provider: aws

    backupStorageLocation:
      name: aws
      bucket: <SPACES_NAME> 
      prefix:
      config:
        region: <SPACES_REGION>
        s3Url: https://<SPACES_REGION>.digitaloceanspaces.com
    volumeSnapshotLocation:
      name: velero.io/aws
      config: {}
    backupSyncPeriod:
    resticTimeout:
    restoreResourcePriorities:
    restoreOnlyMode:
    extraEnvVars: {}
    logLevel:
    logFormat:
  rbac:
    create: true
    clusterAdministrator: true
  serviceAccount:
    server:
      create: true
      name:
      annotations:


  credentials:
    useSecret: true
    existingSecret:
    secretContents:
      digitalocean_token: <DIGITAL_OCEAN_TOKEN>
      cloud: | 
        [default]
        aws_access_key_id=<SPACES_ACCESS_KEY>
        aws_secret_access_key=<SPACES_SECRET_KEY>
 

  backupsEnabled: true
  snapshotsEnabled: true

  deployRestic: false

  restic:
    podVolumePath: /var/lib/kubelet/pods
    privileged: false
    priorityClassName: {}
    resources: {}
    tolerations: []
    extraVolumes: []
    extraVolumeMounts: []
    securityContext: {}
  schedules: {}
  configMaps: {}

